# Generated by Django 2.1.2 on 2018-10-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0004_auto_20181021_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
